#+BEGIN_COMMENT
.. title: The Peculiar Blindness of Experts
.. slug: the-peculiar-blindness-of-experts
.. date: 2020-09-07 17:59:59 UTC-07:00
.. tags: bibliography,experts,forecasting
.. category: Forecasting
.. link: 
.. description: 
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
* Citation
  - Epstein D. The Peculiar Blindness of Experts [Internet]. The Atlantic. 2019 [cited 2020 Sep 7]. Available from: https://www.theatlantic.com/magazine/archive/2019/06/how-to-predict-the-future/588040/
* Commentary
** The Bet
   Paul R. Ehrlich predicted that population increases would cause scarcity and starvation and pushed for regulations to protect the environment and resources. Julian Simon predicted that technological innovation would solve the scarcity problem and clean up the environment. They placed a bet based on the price of five metals which they used as a proxy for resource scarcity. Ehrlich lost the bet but doubled-down on his predictions, saying the timing was off. Later studies showed that the price of metals didn't reflect scarcity and Simon just had the luck of the market. Ehrlich was wrong on scarcity but right on the need for regulation to protect the environment. Simon was right that technology would prevent the catastrophe Ehrlich predicted but couldn't concede that it was regulation and not technology that helped the environment.
** Tetlock's Study
Philip Tetlock set up a study where he collected the predictions of experts on political science for twenty years. At the end of it he found that they were generally horrible at forecasting and that even when shown their predictions, the experts wouldn't concede that they were wrong. The experts tended to make predictions based on their political identifications but one group took ideas from multiple camps and were more successful at making predictions. Tetlock named the two types of experts /Hedgehogs/ and /Foxes/.

| Hedgehog         | Fox                |
|------------------+--------------------|
| specialized      | integrative        |
| know "one thing" | know "many things" |
| narow            | broad              |

The more experienced Hedgehogs became the more they tended to use their added knowledge to bend reality to fit their view.

See this wikipedia page - [[https://en.wikipedia.org/wiki/The_Hedgehog_and_the_Fox][the Hedgehog and the Fox]] - for the source of those terms.

/Multa novit vulpes, verum echinus unum magnum/ - "a fox knows many things, but a hedgehog one important thing".
** The Prediction Tournament

IARPA saw Tetlock's study and set up a prediction tournament to test expert teams. Tetlock entered using volunteers identified as Foxes and won. The Foxes tended to see teammates as sources of information to learn from, while Hedgehogs saw teammates as adversaries who needed to be convinced of their opinions. Both Foxes and Hedgehogs saw successes as reinforcing what they believed, but when information came up that conflicted with those beliefs the Foxes updated their positions while the Hedgehogs doubled-down on their prior beliefs instead.
