#+BEGIN_COMMENT
.. title: Measuring Narrative
.. slug: measuring-narrative
.. date: 2020-09-04 17:22:11 UTC-07:00
.. tags: slipnote,story
.. category: Story
.. link: 
.. description: Metrics for narrative quality.
.. type: text
.. status: 
.. updated: 
.. has_math: true
#+END_COMMENT

The book {{% doc %}}narrative-is-everything{{% /doc %}} has two metrics that the author, Randy Olson suggests using to measure the narrative quality of a text.

** Narrative Index
   This is the ration of /Buts/ to /Ands/. Although it's stated as a ratio of word counts, it isn't exactly that straightforward as the actual words /and/ or /but/ might not be used, but it's a rough way to examine long texts (he recommends not using it if there are fewer than 1,000 words).

\[
\textrm{Narrative Index} = \frac{\textit{number of 'buts'}}{\textit{number of ands}} \times 100
\]

The higher the value the better the narrative quality.

** And Frequency
   This is just a measure of the fraction of the words in a text that are the word /and/.

\[
\textrm{And Frequency} = \frac{\textit{number of 'ands'}}{\textit{total word count}}
\]

Well-edited texts have an /And Frequency/ of about 2.5%.
