#+BEGIN_COMMENT
.. title: Changing the Nikola Bootswatch Theme
.. slug: changing-the-nikola-bootswatch-theme
.. date: 2016-12-30 15:03:38 UTC-08:00
.. tags: HowTo Nikola
.. category: HowTo
.. link: 
.. description: How to change the nikola bootswatch theme.
.. type: text
#+END_COMMENT

I had my theme for this site set to use [[http://nickmccurdy.com/bootswatch/spacelab/][Spacelab]], which I liked, but the gradients were starting to annoy me so I decided to switch to [[http://nickmccurdy.com/bootswatch/journal/][Journal]], which matches my aesthetic tastes a little better. This took more work than I thought it would (mostly because I don't mess with the /nikola/ configuration very often). So these are my notes for the next time.

* Overview
  1. Install the [[https://themes.getnikola.com/#bootstrap3][bootswatch 3]] theme (if you haven't already) (=nikola install_theme bootstrap3=).
  2. Install the [[https://bootswatch.com/journal/][journal]] theme (=nikola bootswatch_theme -s journal=).
  3. Get the base template (=nikola theme -c base.tmpl=).
  4. In =base.tmpl=, change =navbar-inverse= to =navbar-default=.
  5. Change the anchor color in =bootstrap.css= to something less creamsicle.
  6. Build the posts (=nikola build=).
  7. Admire the fruits of your (well, okay, other people's) labor.
* Installing the theme
** The Bootswatch 3 Theme
   I already had the bootswatch 3 theme installed, since I was using /Spacelab/ but in the case of a fresh start, the base theme is set using:

  #+BEGIN_SRC sh
    nikola install_theme bootstrap3
  #+END_SRC

** The Journal Theme
   Since I want to change the theme to /Journal/ this is the next step (you can also specify a parent theme, but the default is =bootstrap3=, which is what I used):
   #+BEGIN_SRC sh
     nikola bootswatch_theme -s journal
   #+END_SRC

   This will set up the default bootstrap theme, but you need to re-build the HTML to have it show up on the web-page (something that I didn't realize initially, causing me to think something was broken).

   #+BEGIN_SRC sh
     nikola build    
   #+END_SRC

* Updating the Template
  On re-loading the page I found that it mostly worked, but for some reason it looked more orange than I expected. It turns out that the /nikola/ developer decided that =navbar-inverse= should be the default style for the navbar (instead of =navbar-default=) and the section headers are hyperlinks, which in the /Journal/ theme are orange (by orange I really mean something closer to a creamsicle). Following the instructions in this [[https://github.com/getnikola/nikola/issues/2552][bug report]] (which says that it isn't a bug, it's a feature) I copied the base template from the /nikola/ installation (in =site-packages=) into the site using a built-in /nikola/ command.

  #+BEGIN_SRC sh
    nikola theme -c base.tmpl
  #+END_SRC

  This command creates a file (=themes/custom/templates/base.tmpl=) which you can edit to override the built-in base template. I opened it up and changed the =navbar-inverse= CSS class to =navbar-default=, re-built the /nikola/ posts, and reloaded the page and there it was, the white navbar I wanted.
* Updating the CSS
  "Fixing" the headlines was more straight-forward. When you install the /journal/ theme it installs a file at =themes/custom/assets/css/bootstrap.css= (along with a mini-fied version) which you can edit. I decided to leave the anchor-hover value the same but changed the plain anchor color to =#990033= so that it's more of a blood red than a creamsicle.
* Summary
  Changing the bootswatch theme isn't as hard as it seemed, in retrospect. You just have to know the basic commands (=nikola install_theme bootstrap3=, =nikola bootswatch_theme -s journal=), know that the inverse navbar is the default (and how to change it - =nikola theme -c base.tmpl=), know how to update the CSS to whatever you want (by editing =bootstrap.css=), and understand that you have to build the site to get it working (=nikola build=).
