#+BEGIN_COMMENT
.. title: How To Take Smart Notes
.. slug: bibliography-how-to-take-smart-notes
.. date: 2018-12-15 10:48:43 UTC-08:00
.. tags: notes,bibliography
.. category: Bibliography
.. link: 
.. description: A reference for the book /How To Take Smart Notes/.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 1
* Reference
  [HTTSN] Ahrens S. How to take smart notes: one simple technique to boost writing, learning and thinking: for students, academics and nonfiction book writers. North Charleston, SC: CreateSpace; 2017. 170 p. 
* Description
  This book describes the /Slip-Box/ method developed by Niklas Luhmann. Its focus is on research writing, but seems like a good system for projects in general. It points that people are generally taught that you should work in a series of "next-steps", but if you are doing something creative (or at least something you haven't done before) then this is an impractical, if not impossible, way to work. Instead the author proposes that you use a system of note-taking to capture everything and then look for patterns in your notes - a bottoms-up approach rather than a top-down one.
