#+BEGIN_COMMENT
.. title: Coding Strip
.. slug: coding-strip
.. date: 2021-01-27 16:46:53 UTC-08:00
.. tags: bibliography,comics,coding comics
.. category: Bibliography
.. link: 
.. description: 
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
* Abstract
  Programming is difficult for some people to learn because the concepts are abstract and while there have been efforts to make them more concrete, efforts that focused either on telling stories (e.g. picture books and adventure comics) or transforming the code into something more tangible (e.g. manipulating physical blocks or using graphic representations to create programs) but these prior works didn't make the step from the concrete systems they created to actual code so this team created and tested a system (Coding Strips) to develop comics that could be directly tied to real code.

* Cite
  - Suh S, Lee M, Xia G. Coding strip: A pedagogical tool for teaching and learning programming concepts through comics. In2020 IEEE Symposium on Visual Languages and Human-Centric Computing (VL/HCC) 2020 Aug 10 (pp. 1-10). IEEE.
