#+BEGIN_COMMENT
.. title: Neural correlates of maintaining one's political beliefs in the face of counterevidence
.. slug: neural-correlates-of-maintaining-ones-political-beliefs-in-the-face-of-counterevidence
.. date: 2020-09-08 18:36:22 UTC-07:00
.. tags: bibliography,psychology,neuroscience,changing minds
.. category: 
.. link: 
.. description: 
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
* Citation
 - Kaplan JT, Gimbel SI, Harris S. Neural correlates of maintaining one’s political beliefs in the face of counterevidence. Scientific reports. 2016 Dec 23;6:39589. [[https://www.nature.com/articles/srep39589][nature.com]]
* Abstract
** Context
People often discount evidence that contradicts their firmly held beliefs. 
** Conflict
However, little is known about the neural mechanisms that govern this behavior. 
** Consequence
*** Method
 We used neuroimaging to investigate the neural systems involved in maintaining belief in the face of counterevidence, presenting 40 liberals with arguments that contradicted their strongly held political and non-political views. 
*** Results
 Challenges to political beliefs produced increased activity in the default mode network—a set of interconnected structures associated with self-representation and disengagement from the external world. Trials with greater belief resistance showed increased response in the dorsomedial prefrontal cortex and decreased activity in the orbitofrontal cortex. We also found that participants who changed their minds more showed less signal in the insula and the amygdala when evaluating counterevidence. These results highlight the role of emotion in belief-change resistance and offer insight into the neural systems involved in belief maintenance, motivated reasoning, and related phenomena.

