#+BEGIN_COMMENT
.. title: Choose Your Own Future
.. slug: choose-your-own-future
.. date: 2020-05-08 19:52:32 UTC-07:00
.. tags: future,schule
.. category: Future
.. link: 
.. description: The first assignment for the Futures Thinking course.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+OPTIONS: H:5
#+TOC: headlines 2
* Problem
*Choose two future topics* to explore in the course, and *identify one question* you have about each future topic.

For example:

 - If your topic is *the future of work*, your question might be: /What will be the most common job in the future that doesn't exist yet today?/
 - If your topic is *the future of augmented reality*, your question might be: /What are the dangers and potential harms of augmented reality to society?/
 - If your topic is *the future of money*, your question might be: /How likely is it that cryptocurrencies will replace traditional national currencies?/
 - If your topic is *the future of religion, you might ask: /How could virtual reality change religious traditions in the future?/

Choose *two* topics, and ask *one* question for each *topic*.
* Review Criteria
Your assignment will be checked for:

- Have you chosen two different future topics, that can be described as "the future of _______"?
- Have you identified one question for each topic, that you hope to learn more about during this course?
* Instructions
1. Pick your *FIRST* future topic.
   I'm interested in the future of Machine Learning.

2. Write a question you have about this topic. What possibility or uncertainty about this future would you like to explore?
   A question I have about this future is: "What will we learn about humanity by teaching machines to mimic thinking?"

3. Pick your *SECOND* future topic.
   I'm also interested in the future of work.

4. Write a question you have about this topic. What possibility or uncertainty about this future would you like to explore?

A question I have about this future is: Will we continue to have rigid work weeks and formal employers or are we evolving into a newer, more nebulous model of employment?

