#+BEGIN_COMMENT
.. title: ProtonPass: Finding the Suggested Password
.. slug: protonpass-finding-the-suggested-password
.. date: 2025-04-19 15:57:25 UTC-07:00
.. tags: howto,proton
.. category: HowTo
.. link: 
.. description: Finding a password suggested by ProtonPass.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

* What This Is About

I'm using [[https://proton.me/pass][Proton Pass]] as one of my password managers and noticed today that it thought my [[https://www.hoopladigital.com/][Hoopla]] password was weak so I decided to change it. While I was changing my password ProtonPass stepped in and gave me a suggested password to use so I figured I'd try it out. Unfortunately their implementation is unintuitive to me and I spent a little while thinking I had just locked myself out of my account and was going to have to go through a password reset. Hoopla's password reset process isn't particularly hard, but it seemed like a good idea to figure out what was going on before I locked myself out of a more critical site, so here's my notes for getting the password from ProtonPass.

* The Start Of the Trouble

When I went to change my password on Hoopla ProtonPass popped up a prompt giving me a new random password like in the screenshot below.

[[lazy-img-url:hoopla-change-password.avif]]

I usually ignore it but for some reason I tried it out this time, clicking on the box to enter the password and then saving it (I took this screenshot later so that isn't my password, in case you're wondering). I confirmed that my old password no longer worked, but when I tried to use Proton Pass to fill in the new password it turned out that it hadn't updated its record with the new one it gave me so it appeared that I had changed my password and then thrown the new one away.

This seemed like an illogical thing to do so I did a little search on the web and found [[https://www.reddit.com/r/ProtonPass/comments/158arja/comment/jtcrvvx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button][this response]] to a [[https://www.reddit.com/r/ProtonPass/comments/158arja/suggest_but_not_save_password/][Reddit post]] confirming that this is, in fact, the way Proton Pass works, but that you can get the new password after the fact from the Firefox extension.

* Getting It Out Of Proton Pass

** The Firefox Extension

I'm using Firefox (on Ubuntu) and the ProtonPass extension, so I clicked on the little purple diamond to bring it up.

[[lazy-img-url:proton-pass-00-firefox-toolbar.avif]]

** Add New Item

This is what the extension showed (with some of my information blocked out). To get to the password you have to (rather unintuitively) click on the purple "+" symbol next to the search box which is the "Add New Item" button. 

[[lazy-img-url:proton-pass-01.avif]]

This brings up a menu, the last item of which is the "Password" option that we want.

[[lazy-img-url:proton-pass-02-menu.avif]]

** Password Generator

Clicking on "Password" brings up a dialog that generates new passwords for you (here giving us a supposedly memorable one). The bottom of that screen, underneath the "Advanced Options" button, is the "Password history" button that we want.

[[lazy-img-url:proton-pass-03-password-dialog.avif]]

** Password History

This shows us the passwords we've generated in the last two weeks. Clicking on the icon for "hoopladigital.com" copied the password I generated for that site to the clipboard which I then used to update the Proton Pass entry for Hoopla so that I could get back into the site.

[[lazy-img-url:proton-pass-04-password-history.avif]]

* Conclusion

Updating the password isn't fantastically difficult, once you know what you have to do, but I don't imagine I'd have figured it out for myself. Hopefully even if I forget how to do it next time I'll at least remember that I wrote down what to do.
