#+BEGIN_COMMENT
.. title: The Kekule Problem (Notes)
.. slug: the-kekule-problem-notes
.. date: 2020-11-24 23:03:04 UTC-08:00
.. tags: notes,essay,mind
.. category: Notes
.. link: 
.. description: Notes on Cormac McCarthy's essay "The Kekule Problem".
.. type: text
.. status: draft
.. updated: 

#+END_COMMENT
* Beginning
  - Kekule solved the structure of the benzene molecule after seeing a snake biting its own tail in a dream : but if the subconscious knows the answer and knows language, why doesn't it just tell us the answer in words? To understand the problem the subconscious must understand language, so why does it use metaphor instead?
  - The Unconcious is a machine for operating an animal- it is a biological system, not so much a "psychological" one.
  - All animals have an unconscious. And in the case of humans it seems to do everything from react to stimuli to solving math problems.
  - Language is useful for explaining problems and solutions, but the actual solving of the problems doesn't use language
  - The way the subconcious works to solve problems, including the everyday problem of speaking, is completely opaque to the conscious mind.
  - Some people think that language is a product of evolution, but if this is the case, how is it that only humans seem to have evolved it?
  - Animals do make use of signals to inform each other, but they don't seem to make the leap to analogy.
  - Language was so useful that it changed our physical form to the point that we are more likely to choke to death because of the placement of the larynx than we would be if the larynx were higher (which would be less useful for speaking)
  - Unlike viruses that invade our brains, language doesn't seem to have an evolutionary path - there was one form, it invaded, and it took us over. There aren't constant mutations trying to invade and succeeding for a bit before failing.
  - But language is problematic, in that it doesn't survive by Darwinism, but rather through Lamarkianism - the best ideas get passed on.
  - The Unconscious seems to be persistent - we get the same dreams repeatedly, as if it is trying to give us a lesson that we don't seem to take.
  - Languages live to describe the world: give it a name, describe it, describe what it does.
  - Oddly, there's no half-formed languages: all languages exist fully formed and they all basically express the same things (even if they differ in the details)
  - The facts of the world come into our unconsciousness and then consciousness turns it into story
  - At some point in history, there was a first person who thought that some "thing" could stand in for another "thing" and thus language was born - not necessarily words - maybe art, maybe stones, etc....
  - The Picture-Form of storytelling favored by the unconscious seems to be superior. You might remember scenes from a story, but do you remember the literal words?
  - When we explain things to people we are translating from the picture-story of the unconscousness to the language of transmission.
  - The unconsciousness is biological, language is learned.
  - The unconsciousness isn't used to giving verbal instructions, and avoids doing it, thus its tendency to give us answers as images when we aren't actively "thinking"
* Middle
* End
  - Citation: {{% doc %}}bib-the-kekule-problem{{% /doc %}}
