#+BEGIN_COMMENT
.. title: Signal of Change
.. slug: signal-of-change
.. date: 2020-05-10 18:09:55 UTC-07:00
.. tags: futures,signals
.. category: Signals
.. link: 
.. description: A Signal of Change.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+OPTIONS: H:5
#+TOC: headlines 2
1. PICK ONE of your two "future of" topics from the previous assignment. This is the topic you will investigate now, to find a signal!

2. DO AN INTERNET SEARCH for "Future of (YOUR TOPIC)". Look for interesting news articles, blog posts, videos, company websites, scientific papers, social media accounts or other recent resources about the topic.

3. EXPLORE YOUR SEARCH RESULTS FOR A "SIGNAL." Remember, a signal is a SPECIFIC EXAMPLE of something that suggests how the world is changing, and how the future could be different. An article about the future of gaming is NOT a signal. A specific example IN the article about a particular new game, or new gaming technolog

y, or new trend in gaming business models, IS a signal. Make sure you find a SPECIFIC EXAMPLE of a new technology, scientific breakthrough, law or regulation, startup company, product or service, or some new problem people are experiencing... a signal is something concrete that is already happening.

4. PICK A SIGNAL and A URL about the signal to include a link to. Others will use the URL to verify the signal exists and investigate the signal further.

5. DESCRIBE THE SIGNAL IN YOUR OWN WORDS. If you were trying to explain it to a random stranger on the street, or a friend, how would you describe it? Think of it as starting a conversation, "Hey, I just learned about the most interesting thing today..." or "I discovered something really weird and new today...!"

6. ANSWER ALL FOUR SIGNALS QUESTIONS ABOUT YOUR SIGNAL. There are no right or wrong answers. Your answers to these questions are thoughtful opinions, informed by your own personal experiences and your knowledge of the topic.
    What kind of change do these signals represent? From what to what?
    What's one driving force, or motivation, behind this change? (Why would someone, or some group, WANT this change?)
    What might be different 10 years from now if this signal becomes more common and widespread?
    Is this a future YOU want to help make? Or a future you'd like to slow down, or prevent?
