#+BEGIN_COMMENT
.. title: Step One: Get the Behavior
.. slug: step-one-get-the-behavior
.. date: 2020-07-31 15:41:00 UTC-07:00
.. tags: slipnote,clicker training,rabbit
.. category: Clicker Training
.. link: 
.. description: Elaborating on the first step of clicker training.
.. type: text

#+END_COMMENT
* Note
The first step of Clicker Training is "Get your rabbit to do what you want it to do", which seems a little ambiguous when you see it on the list, but it breaks down into four basic categories.
** Capture Something She Does on Her Own
   If you see your rabbit do something that she naturally does, like sit up or come to you at certain times, then click and reward it so you can build it up as something she'll do on cue.
** Lure With Food
   If your rabbit will take food from your hand you can teach her to go places by having her follow your hand with food in it, although the next category - /Follow a Target/ - is a preferable way to do this.
** Follow a Target
   Create a target (like a ping-pong ball on the end of a stick) and teach your rabbit to follow it.
   - Start by putting it near her and clicking when she touches it with her nose or mouth
   - Extend it slowly by moving it away from her and rewarding her when she follows it
** Shaping
   The target training follows the /shaping/ pattern, wherein you start by rewarding anything that sort of looks like what you want her to do - like just looking at the target when you show it to her, then progressively extending the behavior needed until it's the one that you want. For example:
   1. look at the target
   2. touch the target
   3. follow the target a little
   4. follow the target further
   5. follow the target into her carrier
* Source
  - {{% lancelot %}}clicking-with-your-rabbit{{% /lancelot %}}
