#+BEGIN_COMMENT
.. title: Python from G to Whatever
.. slug: python-from-g-to-whatever
.. date: 2018-09-29 21:14:41 UTC-07:00
.. tags: python links
.. category: Python
.. link: 
.. description: A subset of links to interesting python stuff.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 1
* Introduction
This [[https://medium.freecodecamp.org/an-a-z-of-useful-python-tricks-b467524ee747?mkt_tok=eyJpIjoiTkRVM1pUbGpNemt4WTJJMCIsInQiOiJFZGVnb1FibHI4NHpJNW1ISHRyM0tNV2hYY2xRcWtud2ZaOHJ0cHR2YXlKc3BmWjFEdjczVDdCbnBsY0FEckhXXC9PSFJwbGJvWTBNNmFBSlwvTVwvV1g3ZWhCVGtCQ3ZNNXoyeWxTdlM4SENWZU1GUWVFRWZZMU15YlwvRzhVNktyMnMifQ%3D%3D][freecodecamp]] article has some references to python stuff the author likes. Not all of it is of interest to me, but some of it is, so this is just my dump of the links I like.
* Links
** Geopy
   [[https://geopy.readthedocs.io/en/stable/#][geopy]] allows you to use python to find out geographic information for locations. It provides a common front end for different services like Google Maps, Bing, etc.
** Inspect
   [[https://docs.python.org/3.5/library/inspect.html][inspect]] is a python built-in that helps you take advantage of python's introspection features. Besides looking at other people's code, it shows you how well (or not) you are providing information for other coders using your code.
** Newspaper
   I haven't actually used [[https://newspaper.readthedocs.io/en/latest/][newspaper]] but it looks interesting.
** sh
   [[https://amoffat.github.io/sh/][sh]] is a subprocess replacement. I've always been kind of leery about using python to run shell commands, but this at least makes it look nicer.
** Wikipedia
   Although wikipedia is one of the classic web-scraping examples, there's actually a [[https://wikipedia.readthedocs.io/en/latest/quickstart.html][python library]] to pull articles more directly.
