#+BEGIN_COMMENT
.. title: Optimization
.. slug: 201207optimization
.. date: 2012-07-20 22:07:00
.. tags: optimization,notes
.. description: Notes on optimization.
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2

* What is Optimization?

/Optimization/ means to find the set of parameters that minimize the cost of a solution to a problem.

* What is a Global Optimization?

A /Global Optimization/ is the optimal solution out of all possible solutions. [PSOAI]

* What is a Local Optimization?

A /Local Optimization/ is a solution that may not be the global optimum but is good enough. [PSOAI]

* What Are the Three Types of Optimization?
- /Exhaustive/: Try all the combinations.
- /Stochastic/: Try a random subset and pick the best.
- /Learning/: Pick random solutions that improve as you go.

* What Is the First Phase of Optimization?
The first phase is to create a mathematical model of the system.

* How Do You Create a Model of the System?

- Translate parameters for the solution to numbers.
- Represent solutions as vectors of parameters.
- Create a cost function that maps the global minimizing parameters to the optimal solution. [PSOAI]

* What is a /Solution/ In Optimization?
A set of parameters that solves the problem with the least cost while still meeting constraints. [IIS]

* What is the /Domain/?
The set of valid parameters (those that solve the problem no matter the cost). [IIS]

* What is the /Feasible Domain/?
The subset of valid parameters that meet the constraints of the problem. [IIS]

* What is a /Feasible Solution/?

A solution that meets all the constraints. [PSOAI]

* What is the /Cost Function/?

A function that maps solutions to their cost (maps the best solution to the best outcome and the worst solution to the worst outcome).


