#+BEGIN_COMMENT
.. title: Recovering From the Ubuntu 18.10 Upgrade
.. slug: recovering-from-the-ubuntu-1810-upgrade
.. date: 2018-10-27 10:40:09 UTC-07:00
.. tags: ubuntu,nvidia,upgrade,repair
.. category: Ubuntu
.. link: 
.. description: Recovering from the unbootable Ubuntu 18.10 problem.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 1
**Note:** I had it hang again on rebooting so there's an update at the end.
* What is this about?
  I updated from Ubuntu 18.04 to [[https://blog.ubuntu.com/2018/10/19/welcome-ubuntu-desktop-18-10][Ubuntu 18.10]] (Cosmic Cuttlefish) last night and upon rebooting found that I couldn't (finish rebooting, that is). In order to write this I had to recover from the problem so I don't have a screen-grab of the error, but it was basically the same one given in [[https://askubuntu.com/questions/837143/failed-to-connect-to-lvmetad][this Stack Overflow post]]:

#+BEGIN_EXAMPLE
WARNING: Failed to connect to lvmetad. Falling back to device scanning.
Volume group "ubuntu-vg" not found
Cannot process volume group ubuntu-vg
WARNING: Failed to connect to lvmetad. Falling back to device scanning.
Reading all physical volumes.  This may take a while...
Found volume group "ubuntu-vg" using metadata type lvm2
WARNING: Failed to connect to lvmetad. Falling back to device scanning.
2 logical volume(s) in volume group "ubuntu-vg" now active /dev/mapper/ubuntu--vg-root: clean, 1180656/30154752 files, 16007858/120604672 blocks
#+END_EXAMPLE

* What didn't work?
  If you read the Stack Overflow post I linked to above, the solution was to downgrade the kernel version using the grub loader so, following that advice, I brought up the Grub menu by holding down the shift key while the machine booted up, then tried to move the cursor down to /Advanced/ in the menu using the arrow keys but for some reason it wouldn't move. I thought maybe it was my [[https://ultimatehackingkeyboard.com/][Ultimate Hacking Keyboard]] so I went and grabbed my [[http://vortexgear.tw/vortex2_2.asp?kind=47&kind2=225&kind3=&kind4=1043][Vortex]] keyboard instead and it still wouldn't work, and at this point some people might think that it probably was not the keyboard, but nope, I went and grabbed my [[http://redragonusa.com/products/keyboard/K552/47][Redragon]] keyboard and all of a sudden it worked. Why did my $30 keyboard work better than my $300 keyboard? And no, I don't think I paid that much when I bought the Ultimate Hacking Keyboard (but it took something like two years to ship so I probably spent more than that in lost time). Well, anyway, it turned out that I plugged the last keyboard in the left USB slot while my other keyboards were in the right USB slot and for some reason the right slot was disabled when I went into the Grub Menu. No mention of that on Stack Overflow, unfortunately.
* What did work?
  While I was googling around I found [[https://askubuntu.com/questions/969917/failed-to-connect-to-lvmetad-stuck-on-boot][this post]] on Stack Overflow where it was mentioned that the solution did mess with the kernel but it also mentions that he purged his nvidia drivers, which struck a chord with me because I've had problems with the nvidia drivers on my computer at work whenever I upgrade so I thought that maybe this might be something to check out first, before messing with the kernel. The post suggested using =ctrl-alt-f3= to get into a terminal which didn't work for me for some reason so I used the Grub Menu instead. Here's the steps for my future self.

 1. Hold the shift key down while the machine boots up
 2. In the Grub Menu use the arrow keys and return to choose the /Advanced/ option
 3. Choose the =(recovery mode)= version of the current kernel (4.18.0)
 4. In the Recovery Menu choose the =root Drop to root shell prompt= option (you have to hit enter again at the next prompt)
 5. The file-system for Recovery Mode is in read-only mode so mount the drive with =mount --options remount,rw /" (you can do this from the Recovery Menu as well, but it's an extra step either way)
 6. Purge the drivers with =apt purge nvidia-*=
 7. Type =exit= then back out of Recovery Mode and finish the startup

I got the stuff about removing the nvidia driver from [[https://askubuntu.com/questions/899309/ubuntu-16-04-how-to-disable-nvidia-driver-from-grub][this Stack Overflow post]]. It took a longer time than I thought it would to start up, but I'm writing this from my machine so it seems to work.
* Anything Else?
  
#+BEGIN_SRC bash :results output :exports both
ubuntu-drivers devices
#+END_SRC

#+RESULTS:
: == /sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0 ==
: modalias : pci:v000010DEd00001402sv00001043sd00008581bc03sc00i00
: vendor   : NVIDIA Corporation
: model    : GM206 [GeForce GTX 950]
: driver   : nvidia-driver-390 - distro non-free recommended
: driver   : xserver-xorg-video-nouveau - distro free builtin
: 

This card actually tended to freeze when I used the open source video drivers that come with Ubuntu so not having the Nvidia drivers seemed like a bad idea. I'm hoping that re-installing them will fix whatever bad setup values were there so I did:

#+BEGIN_EXAMPLE
sudo ubuntu-drivers autoinstall
#+END_EXAMPLE

Cross your fingers.
* Update
  First, I didn't mention it above (because I hadn't noticed) but the bluetooth interface wouldn't start. The GUI actually let me click on the on-switch but nothing changed and when I looked in Journalctl I could see that it was raising errors. Even /hciconfig/ couldn't bring it up. Maddeningly, there are posts out there that showed the same errors that I saw (like [[https://www.queryxchange.com/q/3_772706/bluetooth-problem-after-upgrade-from-ubuntu-14-to-16-04/][this one]]) but not only did none of the fixes they suggested work, but once I rebooted the problem went away, so I could have tried that before troubleshooting, and avoided all the hassle (maybe). 

Of course, every solution creates a problem, and while rebooting fixed my bluetooth interface it also revealed that I had the same problems as before (only my Redragon keyboard really works on the Grub menu and the boot hangs after the initial login to decrypt the disk). I removed the nvidia drivers again and this time I didn't reinstall them before rebooting and now it works, but now I don't know if my GUI is going to start hanging again like it used to. Oh, well, one problem at a time.
