#+BEGIN_COMMENT
.. title: They Say Templates
.. slug: they-say-templates
.. date: 2020-09-05 17:02:44 UTC-07:00
.. tags: slipnote,templates
.. category: Writing
.. link: 
.. description: Templates for what other people say.
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
These are templates for stating what arguments or ideas you are responding to - what "they say".

* Introducting What "They Say"
  - It has become common today to dismiss __.
  - In their recent work, Y and Z have offered harsh critiques of __ for __.

This is specifically for refuting criticisms of another's work.

* Introducing Standard Views
  - __ have always believed that __.
  - Conventional wisdom has it that __.
  - Common sense seems to dictate that __.
  - The standard way of thinking about topic X has it that __.
  - It is often said that __.
  - My whole life I have heard it said that __.
  - You would think that __.
  - Many people assume that __.

This is to challenge widely accepted beliefs.

* Making What "They Say" Something You Say
  - I've always believed that __.
  - When I was a child, I used to think that __.
  - Although I should know better by now, I cannot help thinking that __.
  - At the same time that I believe __, I also believe __.

This is a way to respond to what you used to believe or are ambivalent about.

* Introduce Somenthing Implied or Assumed
  - Although none of them have ever said so directly, __ have often given me the impression that __.
  - One implication of X's treatment of __ is that __.
  - Although X does not say so directly, she apparently assumes that __.
  - While they rarely admit as much, __ often take for granted that.

These help you to look beyond what is being explicitly stated and look for the unstated assumptions and implications of what "they" are saying.
* Introduce an Ongoing Debate
  - In discussions of X, one controversial issue has been __. On the one hand, __ argues __. On the other hand, __ contends __. Others even maintain __. My own view is __.

This both allows you to acknowledge that there isn't a unanimous consensus on the subject and also gives you a chance to explore which side you believe to be correct.

 - When it comes to the topic of __, most of us will readily agree that __. Where this agreement usually ends, however, is on the question of __. Whereas some are convinced that __, others maintain that __.

This opening shows where people agree and disagree on the subject.
* Keep It In View
  Don't just say what you are reacting to just once, remind the reader if it later using what the authors call "return" sentences.

  - In conclusion, then, as I suggested earlier, defenders of __ can't have it both ways. Their assertion that __ is contradicted by their claim that __.

* The Zinczenko Template
  This is based on a fragment from "Don't Blame the Eater" by David Zinczenko.

#+begin_quote
If ever there was an idea custom-made for a Jay Leno monologue, this was it: __. Isn't that like __? Whatever happened to __?

I happen to sympathize with __, though, perhaps because __.
#+end_quote
* Source
  - {{% doc %}}they-sayi-say{{% /doc %}}
