#+BEGIN_COMMENT
.. title: Opinion Mining and Sentiment Analysis
.. slug: opinion-mining-and-sentiment-analysis
.. date: 2020-07-30 13:12:55 UTC-07:00
.. tags: nlp, sentiment analysis,slipnote
.. category: Sentiment Analysis
.. link: 
.. description: Note on what Sentiment Analysis is.
.. type: text

#+END_COMMENT

* Note
An /opinion/ is a subjective statement about what a **person** thinks or believes about **something**.

There are three basic parts needed to understand an opinion:
 1. The opinion holder (**person**)
 2. The opinion target (**something**)
 3. The opinion content

In addition, to make it meaningful, you can add:

 - The Context of the opinion
 - The Sentiment of the opinion

{{% lancelot "(Zhai & Massung, 2016)" %}}text-data-management-and-analysis{{% /lancelot %}}

Sentiment Analysis is a part of Natural Language Processing that looks to transform freeform text into structured data. Opinion is an expression of belief, while sentiment is an expression of feeling. What is sometimes called Sentiment Analysis - the measurement of positive or negative sentiment of a text is really Polarity Classification, a subset of Sentiment Analysis. {{% lancelot "(Pozzi, Fersini, et al., 2017)" %}}sentiment-analysis-in-social-networks{{% /lancelot %}}.


