#+BEGIN_COMMENT
.. title: A Mind For Numbers
.. slug: a-mind-for-numbers
.. date: 2020-09-17 14:37:40 UTC-07:00
.. tags: bibliography,learning
.. category: Bibliography
.. link: 
.. description: 
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
* Citation
  - Oakley BA. A mind for numbers: how to excel at math and science (even if you flunked algebra). New York: Jeremy P. Tarcher/Penguin; 2014. 316 p. 
* Notes
  This is a tour of ideas to help students learn how to learn, with an emphasis on math and science. She covers things varying from how to study, to procrastination, to test-taking. Her ten rules are (paraphrased):

  1. Recall things early and often to make them stick
  2. Used spaced repetition when recalling
  3. Interleave different types of problems so you don't overlearn one type.
  4. Build things into chunks of larger concepts
  5. Explain it like a five year old and use analogies to learn abstract ideas
  6. Test yourself
  7. Focus on one thing at a time
  8. Take breaks
  9. Eat frogs first (do the important but unpleasant things first)
  10. Use mental contrasting (comparing where you are now to where you expect to be) to motivate yourself

There's more in her book than those ten things, but these are the main points, and they sort of touch on her other points even if not stated. She particularly emphasizes chunking and the switching between "focused" and "diffused" modes of thinking, and many of the ideas address how to use both modes while learning.
