#+BEGIN_COMMENT
.. title: Using Your Slip Box
.. slug: using-your-slip-box
.. date: 2018-12-16 11:53:31 UTC-08:00
.. tags: research,notes,method,slip box
.. category: Slip Box
.. link: 
.. description: How to use your Slip Box.
.. type: text
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
* Introduction
This is my re-wording of the Slip Box Method.
* The Method
** Capture Everything  
   Write everything down - ideas don't count until they're out of your head and on paper. Writing it down also frees your mind to move on to other things.
** Take Notes
   Whenever you are taking in someone else's ideas (e.g. reading, listening) take notes.
** Make Your Notes Permanent
   The initial notes are just temporary inputs, later in the day you need to convert them into some form that has these attributes:
    - They are complete - write them for your future self, don't rely on being able to remember what else is needed to understand the note.
    - They are written in a way that relates to your interests.
    - There is only one idea per note.
** Put the Permanent Notes in the Slip Box
   - When you file your note look through the other notes and try and place it behind a related note. 
   - Add links to other notes that are related.
   - Add the new note to an entry-point note that holds links to other notes.
** Work Bottoms-Up
   - Don't try and come up with a project by "thinking", look through the slip box and let it tell you what you're interested in.
   - If you have an idea for what to do but there isn't enough in the box yet, take more notes.
   - Keep the notes in one folder - don't sort them into sub-categories. This way you can make new associations that you didn't have when you first made the note.
** Build Projects From Copies
   Copy everything that seems relevant to a project folder on your desktop and see what needs to be filled in and what seems redundant (or maybe just wrong).
** Translate Your Notes
   Take these fragmented notes and convert them into a coherent argument. If you can't then look to take more notes to fill in what's missing.
** Revise
   Don't accept the first draft, edit, erase, re-do.
** Move On
   When you're done with the project, start over with a new one.
* Implementation Details
  The original method used paper and a wooden box. I really like paper and am tempted to try this, but I don't think doing something that makes me even more if a pack-rat is a good idea. The book ([[https://takesmartnotes.com][How To Take Smart Notes]]) recommends a [[http://www.zettelkasten.danielluedecke.de/en/index.php][computer program]] written specifically for this system, but I am a little leery of getting tied into one program, and all these GUI programs are starting to turn me off.

  Instead, I'm going to try and use this blog as my slip-box, so, as far as "equipment" goes, this is what I'm going to use:

  - [[https://www.gnu.org/software/emacs/][GNU emacs]]
  - [[https://orgmode.org][org-mode]] (comes with emacs)
  - [[https://getnikola.com][Nikola]] (a static site generator)
  - [[https://git-scm.com][git]] (and [[https://pages.github.com][github pages]])

Flattening out the file-system makes it hard to browse the files, though. I guess =less= and =ls= are going to be the main thing I use (and maybe [[https://github.com/ggreer/the_silver_searcher][ag]] and [[https://jblevins.org/projects/deft/][deft]]). We'll see, I only started reading the book yesterday so I'm still trying to figure this out as I go.
* Related Posts
 - [[https://necromuralist.github.io/posts/slip-box-parts-list/][Slip Box Parts List]]
* Reference
 - [[https://necromuralist.github.io/posts/reference/bibliography-how-to-take-smart-notes/][HTTSN]] - How To Take Smart Notes
