#+BEGIN_COMMENT
.. title: Slip Box System Parts List
.. slug: slip-box-system-parts-list
.. date: 2018-12-16 12:33:04 UTC-08:00
.. tags: research,notes,method,slip box
.. category: Slip Box
.. link: 
.. description: The basic parts of a Slip Box system.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
* The Four Parts
** A Capture System
   This should be paper-based, or at least something that's always there and quick to use.
   - a notebook
   - index cards
   - loose paper
   - napkins...
** A Reference System
   This is where you put information about your sources. For books and papers [[https://www.zotero.org][Zotero]] is handy, although once again, the fact that I have to fire up this GUI-based program adds a little bit of overhead. The original system was just another box so I'm going to try something like that. Maybe a sub-folder...
** The Slip Box
   The original system was a wooden box with [[https://papersizes.io/a/a6][A6]] paper. I'm using a static site with plain text (org-mode).
** Something To Produce a Final Product
   The system is aimed at writers, but I'm a computer programmer, and I think it might work with other types of output (like drawing) so it's really just having a way to produce something from your project.
* Related Posts
 - [[https://necromuralist.github.io/posts/using-your-slip-box/][Using the Slip Box]]
* Reference
 - [[https://necromuralist.github.io/posts/reference/bibliography-how-to-take-smart-notes/][HTTSN]] - How To Take Smart Notes

