#+BEGIN_COMMENT
.. title: p5.js With Org-Mode and Nikola
.. slug: p5-js-with-org-mode-and-nikola
.. date: 2019-07-21 16:03:37 UTC-07:00
.. tags: p5.js
.. category: p5.js
.. link: 
.. description: Using p5.js with org-mode and nikola.
.. type: text
.. template: p5.tmpl
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
This is a [[http://p5js.org/][p5]] test based on their [[http://p5js.org/get-started/][get started]] tutorial. It's also an indirect test of using the raw directive to write HTML to pass to nikola.

And now the sketch. If you run your mouse over the blank area you should see a bunch of circles following the cursor.

#+begin_comment
This displays the HTML within the post so the reader can see what it's supposed to look like.
#+end_comment

#+begin_src html
    <div id="get_started">
        <script language="javascript" type="text/javascript" src='get_started.js'></script>
    </div>
#+END_SRC

#+begin_comment
This is the block that gets embedded as actual html when it's exported and is where the p5 sketch ends up.
#+end_comment

#+begin_export html
  <div id="get_started">
  <script language="javascript" type="text/javascript" src='get_started.js'></script>
  </div>
#+end_export

#+include: ../files/posts/processing-test/get_started.js src js

* Notes
This was a little harder than I thought it would be. First, regarding the javascript file:

- In order to get it to the final HTML you need to put in the =listings=
  folder at the root of the nikola folder and use the
  [[https://www.getnikola.com/handbook.html#listing][listing]]
  reStructuredText directive instead of =include= (this is a special
  /nikola/ directive).

And then there's the html trick:

- to get the sketch to stay in the post (instead of showing up on the
  bottom of the page), you have to use the div trick - create a div
  where you want the sketch to be and give it a unique ID (use the =raw=
  /reStructuredText/ to put the HTML tags displayed above into the
  post), then set the parent in the sketch
  (=canvas.parent("get_started")= in this example).
