#+BEGIN_COMMENT
.. title: Encrypt a Disk With Cryptsetup
.. slug: encrypt-a-disk-with-cryptsetup
.. date: 2024-04-16 17:26:20 UTC-07:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
.. status: 
.. updated: 

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 2
* Encrypt

#+begin_example
cryptsetup luksFormat --type luks2 /dev/sda
#+end_example

** Problem: Cryptsetup Not Found

For some reason [[https://forums.raspberrypi.com/viewtopic.php?t=8594#p102801][/usr/local/sbin]] isn't put on the raspberry pi's PATH by default, although that's where apt installs it.

I was going to figure out how to work around it, but it turns out that if you use ~sudo~ then it finds the commands. So, it's there, but if you don't know it's a ~sudo~ command you'll get a confusing error telling you that it doesn't exist, not that you need to run it with ~sudo~. Odd.

** Mapping It

#+begin_example
sudo cryptsetup luksOpen /dev/sda monkeymount
#+end_example

This will create ~/dev/mapper/monkeymount~ which you use to mount the drive (note that it's ~/dev/sda~ not ~/dev/sda1~ (which doesn't exist)).

** Wipe The Contents

#+begin_example
pv -tpreb /dev/zero | sudo dd of=/dev/mapper/monkeymount bs=64K
#+end_example

#+begin_example
dd: error writing '/dev/mapper/monkeymount': No space left on device
<=>                 ]
0+15261648 records in
0+15261647 records out
1000187361280 bytes (1.0 TB, 931 GiB) copied, 41248.4 s, 24.2 MB/s
 931GiB 11:27:28 [23.1MiB/s] [
 <=>              ]
#+end_example

** Create a Filesystem

#+begin_example
sudo mkfs.ext4 /dev/mapper/monkeymount
#+end_example

#+begin_example
mke2fs 1.46.2 (28-Feb-2021)
Creating filesystem with 244186367 4k blocks and 61046784 inodes
Filesystem UUID: c354fde8-2b78-44c1-afbc-cb871012b7d1
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 
        102400000, 214990848

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done     
#+end_example

** Mount It

#+begin_example
sudo mount /dev/mapper/monkeymount /media/data
#+end_example

** Change the Owner to the User

#+begin_example
sudo umount /media/data
sudo chown zenodotus:users /media/data
sudo mount /dev/mapper/monkeymount /media/data
#+end_example

* Links

 - [[https://www.cyberciti.biz/security/howto-linux-hard-disk-encryption-with-luks-cryptsetup-command/][nixCraft]]: ~cryptsetup~ instructions.
