#+BEGIN_COMMENT
.. title: Install Chrome Extensions in Vivaldi
.. slug: install-chrome-extensions-in-vivaldi
.. date: 2017-01-11 22:00:14 UTC-08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

This was taken from the [[http://forum.vivaldi.net/topic/1896/how-to-install-lastpass-for-vivaldi][vivaldi forums]]. It explains how to install the /LastPass/ extension into the [[https://vivaldi.com][vivaldi browser]] and should work for other plugins as well (although I haven't tried yet).

* The Procedure
  1. Install the [[https://github.com/Rob--W/crxviewer][Chrome extension source viewer (CRX Viewer)]] in Chrome
  2. Go to the Chrome Web Store and search for the /LastPass/ extension
  3. Right click on the /LastPass/ search result to bring up the context menu
  4. In the context menu selecte /View extension source/
  5. In the page that opens, click on the /Download/ link in the upper corner
  6. Go to the /Downloads/ folder and make a new folder (e.g. =mkdir lastpass=)
  7. Move the zip-file that you downloaded into the folder (mine was called =hdokiejnpimakedhajhdlcegeplioahd.zip= so I assume the names are random)
  8. Unzip the download
  9. Re-name =_metadata= to =metadata= (the post suggests deleting it, so that might work too)
  10. In /Vivaldi/, open the link /vivaldi://chrome/extensions/
  11. Click the /Developer mode/ checkbox
  12. Click on /Load unpacked extension/
  13. Select the folder you unpacked the zip file into (=lastpass= in this case)
  14. Configure Last Pass
* Conclusion
  This gives the procedure for installing extensions like /LastPass/ into the /Vivaldi/ browser. In the course of writing this up I found out that you don't need to do this for all the extensions (just the ones with leading underscores in some of their folder names, I think). For other extensions just install them from the store - they seem to work out of the box.
