#+BEGIN_COMMENT
.. title: Networking Tools
.. slug: networking-tools
.. date: 2018-05-22 13:57:42 UTC-07:00
.. tags: networking,wireless,tools
.. category: Wireless Tools
.. link: 
.. description: A place to keep information about network monitoring programs.
.. type: text
#+END_COMMENT

* Packet Capturing
** [[http://staff.washington.edu/corey/gulp/][Gulp]]
   Gulp purports to be better at capturing packets than tcpdump (although they can work together).

There is more than one version out there:

 -[[Https://github.com/gsson/gulp][ This one]] says it applied a patch to it five years ago. 
 - [[https://github.com/aokunev/gulp-v01][This one]] says it is the original but hasn't been updated in six years.
 - [[http://blog.crox.net/archives/72-gulp-tcpdump-alternative-for-lossless-capture-on-Linux.html][This blog post]] has updated versions of it including one in 2017 that says it has a major bug fix (but I don't know if it's a gulp bug or not)

** [[https://www.tcpdump.org][tcpdump]]
   More easily obtainable and better documentation available (although still not enough).
** [[http://ssldump.sourceforge.net][ssldump]]
   Captures packets and decodes SSL/TLS packets.
* Packet Examining
** [[https://github.com/mschiffm/cppip][Compressed PCAP Packet Indexing Prograpm (cppip)]]
   This adds indexing to [[http://www.htslib.org/doc/bgzip.html][bgzip]] compressed LibPCAP files which then lets you extract them while the original files are still compressed.
** [[https://linux.die.net/man/8/tcpslice][tcpslice]]
   This lets you extract part of or combine files created by tcpdump when using file rotation.
** [[https://github.com/jpr5/ngrep][ngrep]]
   Describes itself as like GNU grep but for packets.
** [[https://github.com/signed0/pylibpcap][pylibpcap]], [[https://github.com/pynetwork/pypcap][pypcap]]
   Python code to work with libpcap.
** WireShark
   These are installed when you install wireshark.
*** [[https://www.wireshark.org/docs/man-pages/tshark.html][tshark]]/[[https://www.wireshark.org][wireshark]]
   Packet capturing and examining (better documented than most of the other programs)
*** [[https://www.wireshark.org/docs/man-pages/reordercap.html][reordercap]]
   Reorders the packets by timestamp.
*** [[https://www.wireshark.org/docs/man-pages/capinfos.html][capinfos]]
    This prints summary information about packe files (works with gzipped files).
*** [[https://www.wireshark.org/docs/man-pages/mergecap.html][mergecap]]
    Merges multiple packet files together. Mergecap will try to keep timestamps in order when merging, but it assumes each individual file to merge is already in order.
* Packet Flows
** [[http://tcpick.sourceforge.net][tcpick]]
   Track, reassemble, reorder TCP streams.
** [[http://www.tcptrace.org][tcptrace]]
   Gives connection information taken from a capture file.

** [[https://github.com/simsong/tcpflow][tcpflow]]
   Separates out TCP flows into separate files.
* Capture Summarizing
** [[https://www.wireshark.org/docs/man-pages/capinfos.html][capinfos]]
** [[https://github.com/kohler/ipsumdump][ipsumdump]]
   Summarizes packet information in ASCII format
** [[http://www.draconyx.net/articles/tcpdstat-fixing-a-compilation-bug-and-using-statistics.html][tcpdstat]]
   Gives summary statistics for a pcap file
* Network Monitoring
** [[https://www.ntop.org][ntop]]
   Like top but for the network.
** [[http://man7.org/linux/man-pages/man8/ss.8.html][ss (socket statistics)]]
   Part of [[https://en.wikipedia.org/wiki/Iproute2][iproute2]]
* Miscellaneous
** [[http://tcpreplay.appneta.com/][tcpreplay]]
   A suite of programs to edit and replay pcap files.
** [[https://en.wikipedia.org/wiki/Netcat][netcat]]
   Read from and write to TCP/UDP network connections.
** [[https://linux.die.net/man/1/socat][socat]]
   Route data between byte streams.
