#+BEGIN_COMMENT
.. title: Org To Jupyter Notebook
.. slug: org-to-jupyter-notebook
.. date: 2017-04-13 20:00:28 UTC-07:00
.. tags: org-mode,jupyter,emacs
.. category: HowTo
.. link: 
.. description: Converting an org-mode file to a jupyter notebook.
.. type: text
#+END_COMMENT

I've grown to really like [[http://orgmode.org][org-mode]], particularly with [[https://github.com/gregsexton/ob-ipython][ob-ipython]], but there are times when a real Jupyter notebook is better - if you want to render it on github or use the =%matplotlib notebook= feature, for instance. I found a blog post the [[http://kitchingroup.cheme.cmu.edu/blog/2017/01/21/Exporting-org-mode-to-Jupyter-notebooks/][Kitchin Research Group site]] announcing the creation of an exporter and this is some documentation about how to set it up.

* Download

  When I originally set this up it was only available from a link on the blog-post, but it has since been added to a much larger github repository called [[https://github.com/jkitchin/scimax][scimax]]. I'm assuming this is where the latest version will be kept. Unfortunately there's no license so I don't think you can fork the repository, even more importantly, I can't get it to work, so skip it for now and grab the old one.

#+BEGIN_EXAMPLE
cd ~/.emacs.d
mkdir lisp
wget http://kitchingroup.cheme.cmu.edu/media/ox-ipynb.el
#+END_EXAMPLE

* Install

  Make sure that the lisp folder is in the emacs path by putting this line in =init.el=.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp")
#+END_SRC

Also make sure that it's loaded by putting this in =init.el=.

#+BEGIN_SRC emacs-lisp
(require 'ox-ipynb)
#+END_SRC

* Use
  
  In your org-mode file use the =export-ipython= function to export it to an =ipynb= file.

#+BEGIN_SRC emacs-lisp
M-x export-ipynb-buffer
#+END_SRC

Note that this will only work if you have [[https://github.com/gregsexton/ob-ipython][ob-ipython]] installed and at least one ipython code block in the org-file.

#+BEGIN_SRC org
#+BEGIN_SRC ipython :session
print("a")
,#+END_SRC
#+END_SRC
