#+BEGIN_COMMENT
.. title: Org-Babel Stderr Results
.. slug: org-babel-stderr-results
.. date: 2017-01-11 22:53:13 UTC-08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

If you execute a code-block in org-mode the default behavior when the executed code sends output to =stderr= is to open a pop-up buffer rather than including it in the org-babel file. Sometimes, though, you might want to document actual output from =stderr= but, as it turns out, this is how /org-mode/ is designed so you are mostly stuck with it. There is a simple work-around though, just put an entry in the source-block that outputs to =stdout= at the end of the block and everyhing will show up in the results.

This is how you could include the output when there are failing tests run by [[http://docs.pytest.org/en/latest/][py.test]]:

#+BEGIN_SRC org
  #+BEGIN_SRC sh :results verbatim
    py.test tests/
    echo
  ,#+END_SRC
#+END_SRC

This will run all the tests in the =tests= folder and include the output in the /org-mode/ file even if there are failures, thanks to the =echo= at the end.

I got this from [[https://stackoverflow.com/questions/27304469/capturing-the-output-of-diff-with-org-babel][Stack Overflow]], of course.
