#+BEGIN_COMMENT
.. title: The Alphabet Peg
.. slug: the-alphabet-peg
.. date: 2020-07-29 19:54:16 UTC-07:00
.. tags: memory,mnemonic,peg system,slipnote
.. category: Memory
.. link: 
.. description: The Alphabet Peg System for memorizing lists.
.. type: text

#+END_COMMENT

This is a type of Mnemonic Peg System that helps you memorize lists using a pre-built Peg List based on the alphabet. It doesn't have to be the alphabet, it can be any ordered list of words that you already have memorized.

First you created a list of words wherein the first letter of each word matches the letters of the alphabet - /Ape, Bat, Crane/, etc. Now whenever you need to memorize a list you associate each item on the list with a word in the alphabet list in order. So if you need to memorize /a loaf of bread, a container of milk, and a stick of butter/ you would do something like this:

| Abecadarium | List              | Link                                                                 |
|-------------+-------------------+----------------------------------------------------------------------|
| Ape         | Loaf of Bread     | King Kong climbing the Empire State Building holding a loaf of bread |
| Bat         | Container of Milk | Supermarket milk jug with a bat in it                                |
| Crane       | Stick of Butter   | A crane choking on a giant stick of butter                           |

Once you've made the associations you can remember the list by starting with Ape and working through the alphabet.

You can also draw the alphabet and use links between them when memorizing the list (e.g. King Kong throws the loaf of bread at the milk jug with a bat in it).

* Bibliography

 - {{% lancelot %}}mnemonic-alphabet-systems{{% /lancelot %}}
 - {{% lancelot %}}memory-craft{{% /lancelot %}}
